package mil.nga.coordinate_parse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-04-22T16:02:40.355Z
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "mil:nga:coordinate_parse", name = "CoordinateParse")
@XmlSeeAlso({us.gov.ic.ism.v2.ObjectFactory.class, mil.nga.coordinate_pair.ObjectFactory.class, mil.nga.security.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CoordinateParse {

    @WebMethod
    @WebResult(name = "ParseLatitudeResponse", targetNamespace = "mil:nga:coordinate_parse", partName = "result")
    public ParseLatitudeResponse parseLatitude(
        @WebParam(partName = "parameters", name = "ParseLatitude", targetNamespace = "mil:nga:coordinate_parse")
        ParseLatitude parameters
    );

    @WebMethod
    @WebResult(name = "ParseCoordPairResponse", targetNamespace = "mil:nga:coordinate_parse", partName = "result")
    public ParseCoordPairResponse parseCoordPair(
        @WebParam(partName = "parameters", name = "ParseCoordPair", targetNamespace = "mil:nga:coordinate_parse")
        ParseCoordPair parameters
    );

    @WebMethod
    @WebResult(name = "GetErrorMessageResponse", targetNamespace = "mil:nga:coordinate_parse", partName = "result")
    public GetErrorMessageResponse getErrorMessage(
        @WebParam(partName = "parameters", name = "GetErrorMessage", targetNamespace = "mil:nga:coordinate_parse")
        GetErrorMessage parameters
    );

    @WebMethod
    @WebResult(name = "ParseLatitudesResponse", targetNamespace = "mil:nga:coordinate_parse", partName = "result")
    public ParseLatitudesResponse parseLatitudes(
        @WebParam(partName = "parameters", name = "ParseLatitudes", targetNamespace = "mil:nga:coordinate_parse")
        ParseLatitudes parameters
    );

    @WebMethod
    @WebResult(name = "ParseLongitudesResponse", targetNamespace = "mil:nga:coordinate_parse", partName = "result")
    public ParseLongitudesResponse parseLongitudes(
        @WebParam(partName = "parameters", name = "ParseLongitudes", targetNamespace = "mil:nga:coordinate_parse")
        ParseLongitudes parameters
    );

    @WebMethod
    @WebResult(name = "ParseLongitudeResponse", targetNamespace = "mil:nga:coordinate_parse", partName = "result")
    public ParseLongitudeResponse parseLongitude(
        @WebParam(partName = "parameters", name = "ParseLongitude", targetNamespace = "mil:nga:coordinate_parse")
        ParseLongitude parameters
    );

    @WebMethod
    @WebResult(name = "ParseCoordPairsResponse", targetNamespace = "mil:nga:coordinate_parse", partName = "result")
    public ParseCoordPairsResponse parseCoordPairs(
        @WebParam(partName = "parameters", name = "ParseCoordPairs", targetNamespace = "mil:nga:coordinate_parse")
        ParseCoordPairs parameters
    );
}
